# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='otherName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
