# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('susu', '0002_auto_20170825_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='client',
            name='dateofbirth',
        ),
        migrations.AddField(
            model_name='client',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 25, 11, 43, 5, 992351, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
