# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susu', '0004_auto_20170825_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
