# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susu', '0005_auto_20170825_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.CharField(max_length=100),
        ),
    ]
